# Generated by Django 4.1.2 on 2022-11-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidador', models.CharField(max_length=20)),
                ('apellido_cuidador', models.CharField(max_length=40)),
                ('DNI_cuidador', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_animal', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('tipo', models.CharField(max_length=40)),
                ('motivo', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('costo', models.IntegerField()),
            ],
        ),
      
    ]
